services:
  languagetool:
    image: silviof/docker-languagetool
    ports:
      - "127.0.0.1:8010:8010"
    deploy:
      resources:
        limits:
          memory: 1g
    mem_limit: 1g
    restart: unless-stopped
